### Create problem
POST http://localhost:3000/problems
Content-Type: application/json

{
    "title": "hello",
    "description": "world",
    "creator": "john_doe"
}

### Get All
GET http://localhost:3000/problems

### Get problem by ID
GET http://localhost:3000/problems/6595c0f4bf36e31891edf1bb

### Update problem 
PATCH http://localhost:3000/problems/6595c0f4bf36e31891edf1bb
Content-Type: application/json

{
  "title": "Updated",
  "description": "johhhhhhhhhhhhhhhhn"
}

### Delete problem
DELETE http://localhost:3000/problems/6595c0f4bf36e31891edf1bb
